version: '3.7'

services:
  db:
    image: mdillon/postgis:11-alpine
    restart: on-failure
    env_file: ../.envs/.env.dev
    volumes:
      - "./.postgrest/development/pgdata:/var/lib/postgresql/data"
    ports:
      - '5433:5432'


  properties:
    build:
      context: ../src/properties
      dockerfile: Dockerfile
    volumes:
      - "../src/properties:/code"
    restart: on-failure
    env_file: ../.envs/.env.dev
    depends_on:
      - db

  nginx:
    image: nginx
    restart: on-failure
    depends_on:
      - properties
    volumes:
      - "./nginx/properties.conf:/etc/nginx/conf.d/properties.conf"
    ports:
      - "81:81" #Properties
