# Generated by Django 3.0.6 on 2020-06-11 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200611_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Car'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Driver'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='passanger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Passenger'),
        ),
    ]
