# Generated by Django 3.0.6 on 2020-06-11 04:43

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200611_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='driver_location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
